### ISSUE TITLE
Git Flow library is not installed on your computer. Click install and follow instructions to install it.

### ISSUE THREAD

**Issue by monirkohi2006** [tsdmrfth/baba-flow#8]
Environment:
Operating System: Window 10
IDE: Latest Stable Build of VS Code
git: git version 2.21.0.windows.1
git-flow: 1.12.0 (AVH Edition)

- git is installed
which git
/mingw64/bin/git
- git-flow is installed 
which git-flow
/usr/bin/git-flow
- git flow help works
git flow help
usage: git flow <subcommand>

Available subcommands are:
   init      Initialize a new git repo with support for the branching model.
   feature   Manage your feature branches.
   bugfix    Manage your bugfix branches.
   release   Manage your release branches.
   hotfix    Manage your hotfix branches.
   support   Manage your support branches.
   version   Shows version information.
   config    Manage your git-flow configuration.
   log       Show log deviating from base branch.

Try 'git flow <subcommand> help' for details.
- All 'Git Flow: *' extension commands fail with error "Git Flow library is not installed on your computer. Click install and follow instructions to install it."

**Comment by viktorsml** [comment]
I have the same problem. Git flow is working fine but the extension doesn't recognize it. Could it be because I installed git on a custom path?

**Comment by stevebeauge** [comment]
I suspect this is due to https://github.com/tsdmrfth/baba-flow/blob/1d1847f28b0c20f0d21732973579f572c35b4cb5/src/init.js#L187

The flow command is `git flow`, not `git-flow` on windows, at least when git is installed using [Git for windows](https://gitforwindows.org/)

**Comment by tsdmrfth** [comment]
Hey friends. Sorry for late response. When i released this project i could find time to develop this project but now unfortunately i have not enough time. I will try to solve issues as soon as i can.

**Comment by MMike17** [comment]
Still have this problem in Décember of 2020 x)

Does someone have a hand made fix ?
Does the extention work when we install gitflow as a standalone ?

**Comment by myfonj** [comment]
I think it should use the `git.path` settings value from settings.json in the VSC profile folder (if it is possible to read preferrences), or query the "Git that is used by VSCode itself" if there is some method to do it.

---
It is possible to have portable instance of VSC (`data` folder next to Code.exe) with portable instance of GIT somewhere nearby. Sadly, many git-related extension just assume git is in the %path% :(
